@startuml Certified GS1 IDs
skinparam responseMessageBelowArrow true

actor "did:...:GS1" as GS1
actor "did:...:Manufacturer" as Manufacturer
entity "did:...:ItemClass" as gtin
entity "did:...:Machine" as Machine
actor User

group Issue Certified Base Number
    Manufacturer -> GS1 : Request GCP\nPresent company details
    GS1 -> GS1 : Verify request and details
    GS1 -> Manufacturer : ISSUE
    note right of GS1
        <b>GCP Credential</b>
        gcp: 4047111
    end note
    Manufacturer -> Manufacturer : ISSUE
    note right of GS1
        <b>PGLN Credential</b>
        epc: urn:epc:id:pgln:4047111.00000
    end note

    GS1 -> Manufacturer : ISSUE
    note right of GS1
        <b>Certified Company Details Credential</b>
        name: European EPC Competence Center,
        legal_form: GmbH,
        trade_register_number: Köln HBR 61026,
        . . . (use existing schema if possible)
    end note
end


group Issue GTIN + Masterdata
    Manufacturer -> gtin ** : create
    Manufacturer -> gtin : ISSUE
    note right of Manufacturer
        <b>GTIN Credential</b>
        epc: urn:epc:idpat:sgtin:4047111.012345.*
    end note
    Manufacturer -> gtin : ISSUE
    note right of Manufacturer
        <b>Item Class Data Credential</b>
        E.g. digital type label
        Common schema? Verified by gs1 core attributes? eClass?
    end note

end

Manufacturer -> Machine ** : Make


group Issue SGTIN
    gtin -> Machine : ISSUE
    note right of gtin
        <b>SGTIN Credential</b>
    end note

    gtin -> Machine : ISSUE
    note right of gtin
        <b>ILMD Credential</b>
        Manufacturing Date/Location,...
    end note
end

User -> Machine : Get ID + masterdata
Machine -> User : Present <b>SGTIN</b>, <b>ILMD</b>

User -> gtin: Get SGTIN issuer's id + masterdata
gtin -> User: Present <b>GTIN</b>, <b>Item Class Data</b> e.g. digital type label



User --> Manufacturer: Check SGTIN issuer's id
Manufacturer --> User: Present <b>PGLN</b>, <b>Company Details</b>, <b>GCP</b>

== IDs Certified, Machine, Manufacturer authenticated, Master Data Trustworthy ==


Machine -> User : Signed Dynamic Data


@enduml
