@startuml
box "Group internal"
participant Group
participant Subsidiary
end box

participant GS1

participant "Verifier Company" as Verifier

group Issue Company Prefix Credential
Group -> GS1: Request "Company Prefix" credential / certificate
GS1 -> Group: Request company master data
Group -> GS1: Send verifiable master data (credential)
GS1 -> GS1: Verify master data and check with internal database
GS1 -> Group: Issue "Company Prefix" credential {prefix="123", issuer="did:xx:GS1"}
end group

group Internal
Group -> Subsidiary: Issue { prefix="123", serial="456", GLN_full="123456", prefix_owner="did:xxx:Group"}
end group

group Verify
Subsidiary -> Verifier: Present GLN credential { prefix="123", serial="456", GLN_full="123456", prefix_owner="did:xxx:Group"}
Verifier -> Group: Request prefix credential {prefix="", issuer="did:xx:GS1}
Group -> Verifier: Send prefix credential presentation {prefix="123", issuer="did:xxx:GS1"}

end group
@enduml