@startuml
box "Group internal"
participant Group
participant Subsidiary
end box

participant GS1

group Issue Company Prefix Credential
Group -> GS1: Request "Company Prefix" credential / certificate
GS1 -> Group: Request company master data
Group -> GS1: Send verifiable master data (credential)
GS1 -> GS1: Verify master data and check with internal database
GS1 -> Group: Issue "Company Prefix" credential
end group

group Internal
Group -> Subsidiary: Issue "allow request GLN from GS1"
end group

group Issue GLN Credential
Subsidiary -> GS1: Request GLN credential
GS1 -> Subsidiary: Request Verifiable Presentation from Prefix Owner
Subsidiary -> GS1: Send Presentation
GS1 -> GS1: Verify that Subsidiary GLN matches Prefix from Issuer DID
GS1 -> Subsidiary: Issue credential for full GLN {prefix="", gln="", prefix_owner="did:xxx:1234" }
Subsidiary -> Subsidiary: Store GLN credential
end group
@enduml